language: go
go:
  - 1.11.x
install:
  - go get github.com/gohugoio/hugo
script:
  - mkdir -p themes/beautifulhugo && git clone https://github.com/halogenica/beautifulhugo.git themes/beautifulhugo
  - hugo --theme beautifulhugo
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: public
  on:
    branch: master
